/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as EventsRouteImport } from './routes/events'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAmenitiesRouteImport } from './routes/admin/amenities'
import { Route as AdminAvailabilityRouteImport } from './routes/admin/availability'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminEnquiriesRouteImport } from './routes/admin/enquiries'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminRoomsRouteImport } from './routes/admin/rooms'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminStaffRouteImport } from './routes/admin/staff'
import { Route as AdminSubscribersRouteImport } from './routes/admin/subscribers'
import { Route as AmenitiesIndexRouteImport } from './routes/amenities/index'
import { Route as AmenitiesSlugRouteImport } from './routes/amenities/$slug'
import { Route as AuthInviteRouteImport } from './routes/auth/invite'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthResetRouteImport } from './routes/auth/reset'
import { Route as RoomsIndexRouteImport } from './routes/rooms/index'
import { Route as RoomsRoomSlugRouteImport } from './routes/rooms/$roomSlug'
import { Route as AdminBookingsIndexRouteImport } from './routes/admin/bookings/index'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAmenitiesRoute = AdminAmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAvailabilityRoute = AdminAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AmenitiesIndexRoute = AmenitiesIndexRouteImport.update({
  id: '/amenities/',
  path: '/amenities/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesSlugRoute = AmenitiesSlugRouteImport.update({
  id: '/amenities/$slug',
  path: '/amenities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthInviteRoute = AuthInviteRouteImport.update({
  id: '/auth/invite',
  path: '/auth/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomSlugRoute = RoomsRoomSlugRouteImport.update({
  id: '/rooms/$roomSlug',
  path: '/rooms/$roomSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsIndexRoute = AdminBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/menu': typeof MenuRoute
  '/admin/amenities': typeof AdminAmenitiesRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/amenities/$slug': typeof AmenitiesSlugRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/rooms/$roomSlug': typeof RoomsRoomSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/amenities/': typeof AmenitiesIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/menu': typeof MenuRoute
  '/admin/amenities': typeof AdminAmenitiesRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/amenities/$slug': typeof AmenitiesSlugRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/rooms/$roomSlug': typeof RoomsRoomSlugRoute
  '/admin': typeof AdminIndexRoute
  '/amenities': typeof AmenitiesIndexRoute
  '/rooms': typeof RoomsIndexRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/admin/bookings': typeof AdminBookingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/menu': typeof MenuRoute
  '/admin/amenities': typeof AdminAmenitiesRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/amenities/$slug': typeof AmenitiesSlugRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/rooms/$roomSlug': typeof RoomsRoomSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/amenities/': typeof AmenitiesIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/events'
    | '/menu'
    | '/admin/amenities'
    | '/admin/availability'
    | '/admin/content'
    | '/admin/enquiries'
    | '/admin/reviews'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/subscribers'
    | '/amenities/$slug'
    | '/auth/invite'
    | '/auth/login'
    | '/auth/reset'
    | '/rooms/$roomSlug'
    | '/admin/'
    | '/amenities/'
    | '/rooms/'
    | '/api/v1/$'
    | '/admin/bookings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/events'
    | '/menu'
    | '/admin/amenities'
    | '/admin/availability'
    | '/admin/content'
    | '/admin/enquiries'
    | '/admin/reviews'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/subscribers'
    | '/amenities/$slug'
    | '/auth/invite'
    | '/auth/login'
    | '/auth/reset'
    | '/rooms/$roomSlug'
    | '/admin'
    | '/amenities'
    | '/rooms'
    | '/api/v1/$'
    | '/admin/bookings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/events'
    | '/menu'
    | '/admin/amenities'
    | '/admin/availability'
    | '/admin/content'
    | '/admin/enquiries'
    | '/admin/reviews'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/subscribers'
    | '/amenities/$slug'
    | '/auth/invite'
    | '/auth/login'
    | '/auth/reset'
    | '/rooms/$roomSlug'
    | '/admin/'
    | '/amenities/'
    | '/rooms/'
    | '/api/v1/$'
    | '/admin/bookings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  EventsRoute: typeof EventsRoute
  MenuRoute: typeof MenuRoute
  AmenitiesSlugRoute: typeof AmenitiesSlugRoute
  AuthInviteRoute: typeof AuthInviteRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetRoute: typeof AuthResetRoute
  RoomsRoomSlugRoute: typeof RoomsRoomSlugRoute
  AmenitiesIndexRoute: typeof AmenitiesIndexRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/amenities': {
      id: '/admin/amenities'
      path: '/amenities'
      fullPath: '/admin/amenities'
      preLoaderRoute: typeof AdminAmenitiesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/availability': {
      id: '/admin/availability'
      path: '/availability'
      fullPath: '/admin/availability'
      preLoaderRoute: typeof AdminAvailabilityRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/amenities/': {
      id: '/amenities/'
      path: '/amenities'
      fullPath: '/amenities/'
      preLoaderRoute: typeof AmenitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities/$slug': {
      id: '/amenities/$slug'
      path: '/amenities/$slug'
      fullPath: '/amenities/$slug'
      preLoaderRoute: typeof AmenitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/invite': {
      id: '/auth/invite'
      path: '/auth/invite'
      fullPath: '/auth/invite'
      preLoaderRoute: typeof AuthInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomSlug': {
      id: '/rooms/$roomSlug'
      path: '/rooms/$roomSlug'
      fullPath: '/rooms/$roomSlug'
      preLoaderRoute: typeof RoomsRoomSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings/': {
      id: '/admin/bookings/'
      path: '/bookings'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AdminBookingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAmenitiesRoute: typeof AdminAmenitiesRoute
  AdminAvailabilityRoute: typeof AdminAvailabilityRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBookingsIndexRoute: typeof AdminBookingsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAmenitiesRoute: AdminAmenitiesRoute,
  AdminAvailabilityRoute: AdminAvailabilityRoute,
  AdminContentRoute: AdminContentRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBookingsIndexRoute: AdminBookingsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  EventsRoute: EventsRoute,
  MenuRoute: MenuRoute,
  AmenitiesSlugRoute: AmenitiesSlugRoute,
  AuthInviteRoute: AuthInviteRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetRoute: AuthResetRoute,
  RoomsRoomSlugRoute: RoomsRoomSlugRoute,
  AmenitiesIndexRoute: AmenitiesIndexRoute,
  RoomsIndexRoute: RoomsIndexRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
